# 站点名称
site_name: 'SSD'
# 仓库链接
repo_url: https://github.com/zjZSTU/SSD.git
# 作者
site_author: 'zhujian'
# 版权信息
copyright: '2020, zhujian'
# 源文件目录
docs_dir: 'docs'
# 生成静态文件目录
site_dir: 'site'
# 额外信息
extra:
    # 版本号
    version: 0.1.0
# 主题
theme: 
    # name: 'readthedocs'
    # name: 'mkdocs'
    name: 'material'
# markdown扩展
markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.arithmatex

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
# 导航
nav:
    - Home: index.md
    - 训练框架:
        - 配置模块:
            - 引言: config/index.md
            - 命令行参数: config/arg_parse.md
            - YAML配置: config/yaml.md
        - 日志模块:
            - 引言: log/index.md
            - 文本日志: log/text_log.md
            - 可视化日志: log/visualization_log.md
        - 数据模块:
            - 引言: data/index.md
            - 图像预处理:
                - 引言: data/transforms/index.md
                - 格式转换: data/transforms/格式转换.md
                - 光度扭曲: data/transforms/光度扭曲.md
                - 图像扩展: data/transforms/图像扩展.md
                - 随机裁剪: data/transforms/随机裁剪.md
                - 随机镜像: data/transforms/随机镜像.md
                - 图像缩放: data/transforms/图像缩放.md
                - 数据标准化: data/transforms/数据标准化.md
                - Compose: data/transforms/Compose.md
            - 数据集操作:
                - 引言: data/datasets/index.md
                - 数据集路径解析: data/datasets/dataset_path.md
                - 数据集加载: data/datasets/dataset_load.md
                - 数据集评估: data/datasets/dataset_eval.md
        - 检测器模块:
            - 引言: model/index.md
        - 优化器模块:
            - 引言: optim/index.md
            - 梯度更新: optim/gradient_update.md
            - 学习率调度: optim/lr_scheduler.md                
        - 辅助模块:
            - 检查点读写: util/checkpoint.md
    - SSD算法:
        - 引言: ssd/index.md
        - 原理解析:
            - 基础网络: ssd/base_network.md
            - 先验框: ssd/prior_boxes.md
            - 匹配策略: ssd/matching_strategy.md
            - 损失函数: ssd/loss_function.md
            - 'Hard Negative Mining': ssd/hard_negative_mining.md
            - variance变量: ssd/variance.md 
            - '300 vs. 512': ssd/300-vs-512.md
        - 具体实现:
            - 命令行操作: ssd/using_command.md
            - 训练:
                - 训练流程: ssd/train_process.md
                - 训练日志: ssd/train_res.md
            - 测试:
                - 测试流程: ssd/test_process.md
                - 测试日志: ssd/test_res.md
            - 使用:
                - 使用示例: ssd/demo_process.md
                - 使用日志: ssd/demo_res.md
            - 输入设置为512: ssd/input-512.md